### PR TITLE
Add cross-compilation for arm64

### PR DESCRIPTION
**Pull request by pavelzw**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This PR adds support for osx_arm64 and linux_aarch64.

### CODE REVIEW

**Comment by naveen521kk** [comment]
@conda-forge-admin, please rerender

**Comment by naveen521kk** [comment]
@conda-forge-admin, please rerender

**Comment by naveen521kk** [comment]
@conda-forge-admin, please rerender

**Comment by pavelzw** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
